name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode SSH key from Base64
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 --decode > /home/ubuntu/.ssh/id_rsa
        chmod 600 /home/ubuntu/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Docker Compose on EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: /home/ubuntu/.ssh/id_rsa
        script: |
          cd /home/ubuntu/deployment
          docker-compose down
          docker-compose up -d
