name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent and key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu  # Ensure this is the correct user for your EC2 instance
        key: ${{ secrets.EC2_KEY }}
        source: "./"
        target: "/home/ubuntu/deployment"

    - name: Deploy Docker Compose on EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu  # Ensure this is the correct user for your EC2 instance
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/deployment
          docker-compose down
          docker-compose up -d